version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  app:
    image: node:20
    container_name: knex-runner
    restart: always
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      - DB_CLIENT=${DB_CLIENT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ENV=${DB_ENV}
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend: