CREATE TABLE problem_validation_runs (
    id TEXT PRIMARY KEY DEFAULT UPPER(REPLACE(uuid_generate_v4()::TEXT, '-', '')),
    problem_id TEXT NOT NULL,
    language_id TEXT NOT NULL,
    source_code TEXT,
    status TEXT NOT NULL,
    compile_output TEXT,
    runtime_msg TEXT,
    memory_msg TEXT,
    error_msg TEXT,
    max_memory TEXT,
    max_time TEXT,
    avg_memory TEXT,
    avg_time TEXT,
    run_by TEXT NOT NULL,
    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by VARCHAR(100) DEFAULT 'SYSTEM',
    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_by VARCHAR(100) DEFAULT 'SYSTEM',
    version INT DEFAULT 1,
    is_deleted BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (problem_id) REFERENCES problems(id) ON DELETE CASCADE,
    FOREIGN KEY (language_id) REFERENCES support_language(id),
    FOREIGN KEY (run_by) REFERENCES users(id) ON DELETE CASCADE
);
